# flake8: noqa

"""
    Swagger Petstore

    This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    The version of the OpenAPI document: 1.0.6
    Contact: apiteam@swagger.io
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from petstore.api_client import ApiClient

# import Configuration
from petstore.configuration import Configuration

# import exceptions
from petstore.exceptions import OpenApiException
from petstore.exceptions import ApiAttributeError
from petstore.exceptions import ApiTypeError
from petstore.exceptions import ApiValueError
from petstore.exceptions import ApiKeyError
from petstore.exceptions import ApiException
